// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsuyvkybrmddtsanvmvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzdXl2a3licm1kZHRzYW52bXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjQzNDksImV4cCI6MjA2NDU0MDM0OX0.vwgiKeTECIVr2WUO1eLaDBeAROHDp3_xWGEfg4oijwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});